# Generated by Django 2.2.6 on 2019-10-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='categorie')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('satut', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
                ('message', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commenter',
                'verbose_name_plural': 'Commenter',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categorie')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('satut', models.BooleanField()),
                ('Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleCommentaire', to='blog.Article')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCommentaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('satut', models.BooleanField()),
                ('Tag_id', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='Categorie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CategorieArticle', to='blog.Categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
