# Generated by Django 2.2.6 on 2019-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Categorie_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='Tag_id',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='Article_id',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='User_id',
        ),
        migrations.DeleteModel(
            name='Commenter',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
